language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - pypy

env:
  - DJANGO_VERSION=1.3.7
  - DJANGO_VERSION=1.4.10
  - DJANGO_VERSION=1.5.5
  - DJANGO_VERSION=1.6.1

matrix:
  exclude:
    - python: 3.3
      env: DJANGO_VERSION=1.3.7
    - python: 3.3
      env: DJANGO_VERSION=1.4.10
    - python: pypy
      env: DJANGO_VERSION=1.3.7
    - python: pypy
      env: DJANGO_VERSION=1.4.10

install:
  - pip install Django==$DJANGO_VERSION
  - pip install -r requirements.txt


script: python setup.py test
